2025-07-25 20:19:53,488 [INFO] core: Saving tenant with schema_name: proliance
2025-07-25 20:20:03,057 [INFO] core: Saving tenant with schema_name: proliance
2025-07-25 20:21:20,572 [INFO] core: Saving tenant with schema_name: public
2025-07-25 20:21:20,590 [INFO] core: Saving tenant with schema_name: public
2025-07-25 20:21:47,301 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-25 20:22:18,373 [INFO] django.server: "OPTIONS /api/token/ HTTP/1.1" 200 0
2025-07-25 20:22:18,694 [ERROR] django.request: Internal Server Error: /api/token/
2025-07-25 20:22:18,696 [ERROR] django.server: "POST /api/token/ HTTP/1.1" 500 58
2025-07-25 20:25:27,264 [INFO] core: Saving tenant with schema_name: public
2025-07-25 20:25:27,288 [INFO] core: Saving tenant with schema_name: public
2025-07-25 20:25:43,068 [INFO] core: Saving tenant with schema_name: proliance
2025-07-25 20:25:54,537 [INFO] core: Saving tenant with schema_name: proliance
2025-07-25 20:27:09,883 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-25 20:27:23,061 [INFO] django.server: "POST /api/token/ HTTP/1.1" 200 985
2025-07-25 20:27:23,101 [INFO] django.server: "OPTIONS /api/token/validate/ HTTP/1.1" 200 0
2025-07-25 20:27:23,401 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 382
2025-07-25 20:27:23,662 [INFO] django.server: "OPTIONS /api/users/stats/ HTTP/1.1" 200 0
2025-07-25 20:27:23,698 [INFO] django.server: "OPTIONS /api/courses/courses/ HTTP/1.1" 200 0
2025-07-25 20:27:23,713 [INFO] django.server: "OPTIONS /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 0
2025-07-25 20:27:23,730 [INFO] django.server: "OPTIONS /api/courses/courses/?page=1&page_size=10 HTTP/1.1" 200 0
2025-07-25 20:27:23,763 [INFO] django.server: "OPTIONS /api/users/user-activities/?limit=10 HTTP/1.1" 200 0
2025-07-25 20:27:23,770 [INFO] django.server: "OPTIONS /messaging/api/messages/unread_count/ HTTP/1.1" 200 0
2025-07-25 20:27:23,777 [INFO] django.server: "OPTIONS /schedule/api/schedules/upcoming/ HTTP/1.1" 200 0
2025-07-25 20:27:23,788 [INFO] django.server: "OPTIONS /payments/payment-config HTTP/1.1" 200 0
2025-07-25 20:27:23,805 [INFO] django.server: "OPTIONS /api/groups/groups/?limit=10 HTTP/1.1" 200 0
2025-07-25 20:27:23,982 [INFO] django.server: "OPTIONS /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 0
2025-07-25 20:27:23,987 [INFO] django.server: "OPTIONS /api/courses/courses/ HTTP/1.1" 200 0
2025-07-25 20:27:23,993 [INFO] django.server: "OPTIONS /api/courses/courses/?page=1&page_size=10 HTTP/1.1" 200 0
2025-07-25 20:27:23,996 [INFO] django.server: "OPTIONS /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 0
2025-07-25 20:27:24,015 [INFO] django.server: "OPTIONS /api/courses/courses/?page=1&page_size=10 HTTP/1.1" 200 0
2025-07-25 20:27:24,016 [INFO] django.server: "OPTIONS /messaging/api/messages/unread_count/ HTTP/1.1" 200 0
2025-07-25 20:27:24,025 [INFO] django.server: "OPTIONS /schedule/api/schedules/upcoming/ HTTP/1.1" 200 0
2025-07-25 20:27:24,026 [INFO] django.server: "OPTIONS /payments/payment-config HTTP/1.1" 200 0
2025-07-25 20:27:24,029 [INFO] django.server: "OPTIONS /api/users/user-activities/?limit=10 HTTP/1.1" 200 0
2025-07-25 20:27:24,034 [INFO] django.server: "OPTIONS /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 0
2025-07-25 20:27:24,035 [INFO] django.server: "OPTIONS /api/groups/groups/?limit=10 HTTP/1.1" 200 0
2025-07-25 20:27:24,046 [INFO] django.server: "OPTIONS /api/courses/courses/?page=1&page_size=10 HTTP/1.1" 200 0
2025-07-25 20:27:24,183 [ERROR] django.request: Internal Server Error: /api/users/stats/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\users\views.py", line 415, in stats
    'new_signups': CustomUser.objects.filter(signup_date__gte=seven_days_ago).count(),
                   ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1526, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1333, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1805, in names_to_path
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Cannot resolve keyword 'signup_date' into field. Choices are: activities, badges, course_ratings, created_adverts, created_categories, created_courses, created_learning_paths, created_schedules, date_joined, email, emailaddress, enrollments, failedlogin, first_name, groupmembership, groups, id, instructor_profile, is_active, is_deleted, is_locked, is_staff, is_superuser, last_login, last_name, logentry, outstandingtoken, password, points, received_messages, role, schedule_participations, sent_messages, socialaccount, status, tenant, tenant_id, user_permissions, userprofile
2025-07-25 20:27:24,223 [ERROR] django.server: "GET /api/users/stats/ HTTP/1.1" 500 29909
2025-07-25 20:27:24,320 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 78
2025-07-25 20:27:24,338 [INFO] django.server: "GET /messaging/api/messages/unread_count/ HTTP/1.1" 200 18
2025-07-25 20:27:24,344 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 20:27:24,347 [INFO] users: [proliance] Retrieved 4 user activity records
2025-07-25 20:27:24,375 [INFO] django.server: "GET /api/users/user-activities/?limit=10 HTTP/1.1" 200 1080
2025-07-25 20:27:24,377 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=10 HTTP/1.1" 200 78
2025-07-25 20:27:24,511 [ERROR] django.request: Internal Server Error: /schedule/api/schedules/upcoming/
2025-07-25 20:27:24,514 [ERROR] django.server: "GET /schedule/api/schedules/upcoming/ HTTP/1.1" 500 46
2025-07-25 20:27:24,677 [INFO] django.server: "GET /messaging/api/messages/unread_count/ HTTP/1.1" 200 18
2025-07-25 20:27:24,682 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 78
2025-07-25 20:27:24,770 [INFO] django.server: "GET /api/groups/groups/?limit=10 HTTP/1.1" 200 648
2025-07-25 20:27:24,811 [ERROR] django.request: Internal Server Error: /api/users/stats/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\users\views.py", line 415, in stats
    'new_signups': CustomUser.objects.filter(signup_date__gte=seven_days_ago).count(),
                   ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1526, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1333, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1805, in names_to_path
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Cannot resolve keyword 'signup_date' into field. Choices are: activities, badges, course_ratings, created_adverts, created_categories, created_courses, created_learning_paths, created_schedules, date_joined, email, emailaddress, enrollments, failedlogin, first_name, groupmembership, groups, id, instructor_profile, is_active, is_deleted, is_locked, is_staff, is_superuser, last_login, last_name, logentry, outstandingtoken, password, points, received_messages, role, schedule_participations, sent_messages, socialaccount, status, tenant, tenant_id, user_permissions, userprofile
2025-07-25 20:27:24,832 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 20:27:24,834 [ERROR] django.server: "GET /api/users/stats/ HTTP/1.1" 500 29912
2025-07-25 20:27:24,980 [ERROR] django.request: Internal Server Error: /payments/payment-config
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "payments_paymentconfig" does not exist
LINE 1: ...d_at", "payments_paymentconfig"."updated_at" FROM "payments_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\payments\views.py", line 54, in list
    config = PaymentConfig.objects.first()
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1104, in first
    for obj in queryset[:1]:
               ~~~~~~~~^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "payments_paymentconfig" does not exist
LINE 1: ...d_at", "payments_paymentconfig"."updated_at" FROM "payments_...
                                                             ^

2025-07-25 20:27:24,986 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=10 HTTP/1.1" 200 78
2025-07-25 20:27:24,986 [INFO] users: [proliance] Retrieved 4 user activity records
2025-07-25 20:27:25,030 [ERROR] django.server: "GET /payments/payment-config HTTP/1.1" 500 30023
2025-07-25 20:27:25,051 [INFO] django.server: "GET /api/users/user-activities/?limit=10 HTTP/1.1" 200 1080
2025-07-25 20:27:25,253 [ERROR] django.request: Internal Server Error: /schedule/api/schedules/upcoming/
2025-07-25 20:27:25,291 [ERROR] django.server: "GET /schedule/api/schedules/upcoming/ HTTP/1.1" 500 46
2025-07-25 20:27:25,305 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 20:27:25,347 [INFO] django.server: "GET /api/groups/groups/?limit=10 HTTP/1.1" 200 648
2025-07-25 20:27:25,501 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=10 HTTP/1.1" 200 78
2025-07-25 20:27:25,585 [ERROR] django.request: Internal Server Error: /payments/payment-config
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "payments_paymentconfig" does not exist
LINE 1: ...d_at", "payments_paymentconfig"."updated_at" FROM "payments_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\payments\views.py", line 54, in list
    config = PaymentConfig.objects.first()
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1104, in first
    for obj in queryset[:1]:
               ~~~~~~~~^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "payments_paymentconfig" does not exist
LINE 1: ...d_at", "payments_paymentconfig"."updated_at" FROM "payments_...
                                                             ^

2025-07-25 20:27:25,588 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 20:27:25,604 [ERROR] django.server: "GET /payments/payment-config HTTP/1.1" 500 30023
2025-07-25 20:27:25,666 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=10 HTTP/1.1" 200 78
2025-07-25 20:28:07,901 [INFO] django.server: "OPTIONS /api/groups/groups/ HTTP/1.1" 200 0
2025-07-25 20:28:07,913 [INFO] django.server: "OPTIONS /api/groups/roles/ HTTP/1.1" 200 0
2025-07-25 20:28:07,915 [INFO] django.server: "OPTIONS /api/groups/roles/ HTTP/1.1" 200 0
2025-07-25 20:28:07,931 [INFO] django.server: "OPTIONS /api/users/users/?page_size=1000 HTTP/1.1" 200 0
2025-07-25 20:28:07,934 [INFO] django.server: "OPTIONS /api/groups/groups/ HTTP/1.1" 200 0
2025-07-25 20:28:07,957 [INFO] django.server: "OPTIONS /api/groups/groups/ HTTP/1.1" 200 0
2025-07-25 20:28:07,986 [INFO] django.server: "OPTIONS /api/groups/roles/ HTTP/1.1" 200 0
2025-07-25 20:28:07,992 [INFO] django.server: "OPTIONS /api/groups/roles/ HTTP/1.1" 200 0
2025-07-25 20:28:08,016 [INFO] django.server: "OPTIONS /api/users/users/?page_size=1000 HTTP/1.1" 200 0
2025-07-25 20:28:08,021 [INFO] django.server: "OPTIONS /api/groups/roles/ HTTP/1.1" 200 0
2025-07-25 20:28:08,031 [INFO] django.server: "OPTIONS /api/groups/roles/ HTTP/1.1" 200 0
2025-07-25 20:28:08,041 [INFO] django.server: "OPTIONS /api/groups/groups/ HTTP/1.1" 200 0
2025-07-25 20:28:08,418 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 78
2025-07-25 20:28:08,449 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 20:28:08,543 [INFO] django.server: "GET /api/users/users/?page_size=1000 HTTP/1.1" 200 410
2025-07-25 20:28:08,652 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-07-25 20:28:08,652 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 648
2025-07-25 20:28:08,752 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 20:28:08,798 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 78
2025-07-25 20:28:08,840 [INFO] django.server: "GET /api/users/users/?page_size=1000 HTTP/1.1" 200 410
2025-07-25 20:28:09,061 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-07-25 20:28:09,063 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 648
2025-07-25 20:28:09,069 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 20:28:09,388 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 20:28:09,426 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-07-25 20:28:09,434 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 648
2025-07-25 20:28:09,656 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 20:28:09,734 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 648
2025-07-25 20:28:09,747 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-07-25 20:28:09,918 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 20:28:09,961 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-07-25 20:28:10,104 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-07-25 20:29:46,954 [INFO] django.server: "OPTIONS /api/courses/enrollments/all/ HTTP/1.1" 200 0
2025-07-25 20:29:46,956 [INFO] django.server: "OPTIONS /api/courses/enrollments/all/ HTTP/1.1" 200 0
2025-07-25 20:29:46,956 [INFO] django.server: "OPTIONS /api/courses/courses/most_popular/ HTTP/1.1" 200 0
2025-07-25 20:29:46,961 [INFO] django.server: "OPTIONS /api/courses/categories/ HTTP/1.1" 200 0
2025-07-25 20:29:46,957 [INFO] django.server: "OPTIONS /api/courses/courses/least_popular/ HTTP/1.1" 200 0
2025-07-25 20:29:46,989 [INFO] django.server: "OPTIONS /api/courses/courses/most_popular/ HTTP/1.1" 200 0
2025-07-25 20:29:47,004 [INFO] django.server: "OPTIONS /api/courses/courses/least_popular/ HTTP/1.1" 200 0
2025-07-25 20:29:47,017 [INFO] django.server: "OPTIONS /api/courses/categories/ HTTP/1.1" 200 0
2025-07-25 20:29:47,221 [INFO] django.server: "GET /api/courses/courses/most_popular/ HTTP/1.1" 200 45
2025-07-25 20:29:47,229 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 78
2025-07-25 20:29:47,260 [INFO] django.server: "GET /api/courses/courses/least_popular/ HTTP/1.1" 200 45
2025-07-25 20:29:47,274 [INFO] django.server: "GET /api/courses/enrollments/all/ HTTP/1.1" 200 52
2025-07-25 20:29:47,282 [INFO] django.server: "GET /api/courses/categories/ HTTP/1.1" 200 52
2025-07-25 20:29:47,423 [INFO] django.server: "GET /api/courses/courses/most_popular/ HTTP/1.1" 200 45
2025-07-25 20:29:47,460 [INFO] django.server: "GET /api/courses/enrollments/all/ HTTP/1.1" 200 52
2025-07-25 20:29:47,470 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 78
2025-07-25 20:29:47,478 [INFO] django.server: "GET /api/courses/courses/least_popular/ HTTP/1.1" 200 45
2025-07-25 20:29:47,500 [INFO] django.server: "GET /api/courses/categories/ HTTP/1.1" 200 52
2025-07-25 20:29:47,563 [INFO] django.server: "OPTIONS /api/courses/courses/?page=1&page_size=1000 HTTP/1.1" 200 0
2025-07-25 20:29:47,563 [INFO] django.server: "OPTIONS /api/courses/courses/?page=1&page_size=1000 HTTP/1.1" 200 0
2025-07-25 20:29:47,874 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=1000 HTTP/1.1" 200 78
2025-07-25 20:29:48,132 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=1000 HTTP/1.1" 200 78
2025-07-25 20:29:51,618 [INFO] django.server: "GET /api/courses/categories/ HTTP/1.1" 200 52
2025-07-25 20:29:51,752 [INFO] django.server: "GET /api/courses/categories/ HTTP/1.1" 200 52
2025-07-25 20:30:06,467 [INFO] django.server: "POST /api/courses/categories/ HTTP/1.1" 201 324
2025-07-25 20:32:51,938 [WARNING] django.request: Bad Request: /api/courses/courses/
2025-07-25 20:32:51,940 [WARNING] django.server: "POST /api/courses/courses/ HTTP/1.1" 400 30
2025-07-25 20:34:49,841 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\utils\storage.py changed, reloading.
2025-07-25 20:34:55,160 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-25 20:35:02,102 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\utils\storage.py changed, reloading.
2025-07-25 20:35:05,331 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-25 20:35:33,755 [WARNING] django.request: Bad Request: /api/courses/courses/
2025-07-25 20:35:33,756 [WARNING] django.server: "POST /api/courses/courses/ HTTP/1.1" 400 30
2025-07-25 20:37:02,488 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\utils\storage.py changed, reloading.
2025-07-25 20:37:06,194 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-25 20:37:47,493 [WARNING] django.request: Bad Request: /api/courses/courses/
2025-07-25 20:37:47,496 [WARNING] django.server: "POST /api/courses/courses/ HTTP/1.1" 400 30
2025-07-25 20:42:52,269 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\lumina_care\settings.py changed, reloading.
2025-07-25 20:42:57,186 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-25 20:45:41,666 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\utils\storage.py changed, reloading.
2025-07-25 20:45:44,845 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-25 20:46:30,613 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\utils\storage.py changed, reloading.
2025-07-25 20:46:34,196 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-25 20:46:52,051 [WARNING] django.request: Bad Request: /api/courses/courses/
2025-07-25 20:46:52,053 [WARNING] django.server: "POST /api/courses/courses/ HTTP/1.1" 400 30
2025-07-25 20:50:36,906 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\utils\storage.py changed, reloading.
2025-07-25 20:50:40,802 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-25 20:50:56,457 [WARNING] django.request: Bad Request: /api/courses/courses/
2025-07-25 20:50:56,458 [WARNING] django.server: "POST /api/courses/courses/ HTTP/1.1" 400 30
2025-07-25 20:52:23,432 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\utils\storage.py changed, reloading.
2025-07-25 20:52:27,316 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-25 20:52:47,795 [INFO] django.server: "POST /api/courses/courses/ HTTP/1.1" 201 1965
2025-07-25 20:52:48,103 [INFO] django.server: "OPTIONS /api/courses/courses/6/ HTTP/1.1" 200 0
2025-07-25 20:52:48,291 [INFO] django.server: "GET /api/courses/categories/ HTTP/1.1" 200 393
2025-07-25 20:52:50,524 [INFO] django.server: "GET /api/courses/courses/6/ HTTP/1.1" 200 2001
2025-07-25 20:52:58,634 [INFO] django.server: "GET /api/courses/enrollments/all/ HTTP/1.1" 200 52
2025-07-25 20:52:58,635 [INFO] django.server: "GET /api/courses/courses/most_popular/ HTTP/1.1" 200 45
2025-07-25 20:52:58,666 [INFO] django.server: "GET /api/courses/courses/least_popular/ HTTP/1.1" 200 45
2025-07-25 20:52:58,684 [INFO] django.server: "GET /api/courses/categories/ HTTP/1.1" 200 393
2025-07-25 20:52:58,820 [INFO] django.server: "GET /api/courses/enrollments/all/ HTTP/1.1" 200 52
2025-07-25 20:52:58,832 [INFO] django.server: "GET /api/courses/courses/most_popular/ HTTP/1.1" 200 45
2025-07-25 20:52:58,860 [INFO] django.server: "GET /api/courses/courses/least_popular/ HTTP/1.1" 200 45
2025-07-25 20:52:58,872 [INFO] django.server: "GET /api/courses/categories/ HTTP/1.1" 200 393
2025-07-25 20:53:00,597 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 2079
2025-07-25 20:53:03,823 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 2079
2025-07-25 20:53:04,103 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=1000 HTTP/1.1" 200 2079
2025-07-25 20:53:06,662 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=1000 HTTP/1.1" 200 2079
2025-07-25 20:53:11,210 [INFO] django.server: "GET /api/courses/courses/6/ HTTP/1.1" 200 2001
2025-07-25 20:53:13,641 [INFO] django.server: "GET /api/courses/courses/6/ HTTP/1.1" 200 2001
2025-07-25 20:53:45,915 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\lumina_care\settings.py changed, reloading.
2025-07-25 20:53:50,820 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-25 21:02:36,174 [INFO] core: Saving tenant with schema_name: render
2025-07-25 21:07:50,139 [INFO] core: Saving tenant with schema_name: render
2025-07-25 21:08:31,709 [INFO] core: Saving tenant with schema_name: proliance
2025-07-25 21:13:24,510 [INFO] core: Saving tenant with schema_name: proliance
2025-07-25 21:15:50,694 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-25 21:16:14,705 [INFO] django.server: "POST /api/token/ HTTP/1.1" 200 985
2025-07-25 21:16:15,044 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 382
2025-07-25 21:16:15,653 [ERROR] django.request: Internal Server Error: /api/users/stats/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\users\views.py", line 415, in stats
    'new_signups': CustomUser.objects.filter(signup_date__gte=seven_days_ago).count(),
                   ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1526, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1333, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1805, in names_to_path
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Cannot resolve keyword 'signup_date' into field. Choices are: activities, badges, course_ratings, created_adverts, created_categories, created_courses, created_learning_paths, created_schedules, date_joined, email, emailaddress, enrollments, failedlogin, first_name, groupmembership, groups, id, instructor_profile, is_active, is_deleted, is_locked, is_staff, is_superuser, last_login, last_name, logentry, outstandingtoken, password, points, received_messages, role, schedule_participations, sent_messages, socialaccount, status, tenant, tenant_id, user_permissions, userprofile
2025-07-25 21:16:15,699 [ERROR] django.server: "GET /api/users/stats/ HTTP/1.1" 500 29912
2025-07-25 21:16:15,887 [INFO] django.server: "GET /messaging/api/messages/unread_count/ HTTP/1.1" 200 18
2025-07-25 21:16:15,941 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 21:16:15,967 [INFO] users: [proliance] Retrieved 8 user activity records
2025-07-25 21:16:15,974 [INFO] django.server: "GET /api/users/user-activities/?limit=10 HTTP/1.1" 200 2099
2025-07-25 21:16:16,005 [ERROR] django.request: Internal Server Error: /schedule/api/schedules/upcoming/
2025-07-25 21:16:16,008 [ERROR] django.server: "GET /schedule/api/schedules/upcoming/ HTTP/1.1" 500 46
2025-07-25 21:16:16,283 [INFO] django.server: "GET /messaging/api/messages/unread_count/ HTTP/1.1" 200 18
2025-07-25 21:16:16,335 [ERROR] django.request: Internal Server Error: /payments/payment-config
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "payments_paymentconfig" does not exist
LINE 1: ...d_at", "payments_paymentconfig"."updated_at" FROM "payments_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\payments\views.py", line 54, in list
    config = PaymentConfig.objects.first()
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1104, in first
    for obj in queryset[:1]:
               ~~~~~~~~^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "payments_paymentconfig" does not exist
LINE 1: ...d_at", "payments_paymentconfig"."updated_at" FROM "payments_...
                                                             ^

2025-07-25 21:16:16,360 [ERROR] django.server: "GET /payments/payment-config HTTP/1.1" 500 30023
2025-07-25 21:16:16,434 [ERROR] django.request: Internal Server Error: /api/users/stats/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\users\views.py", line 415, in stats
    'new_signups': CustomUser.objects.filter(signup_date__gte=seven_days_ago).count(),
                   ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1526, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1333, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1805, in names_to_path
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Cannot resolve keyword 'signup_date' into field. Choices are: activities, badges, course_ratings, created_adverts, created_categories, created_courses, created_learning_paths, created_schedules, date_joined, email, emailaddress, enrollments, failedlogin, first_name, groupmembership, groups, id, instructor_profile, is_active, is_deleted, is_locked, is_staff, is_superuser, last_login, last_name, logentry, outstandingtoken, password, points, received_messages, role, schedule_participations, sent_messages, socialaccount, status, tenant, tenant_id, user_permissions, userprofile
2025-07-25 21:16:16,453 [ERROR] django.server: "GET /api/users/stats/ HTTP/1.1" 500 29912
2025-07-25 21:16:16,532 [INFO] django.server: "GET /api/groups/groups/?limit=10 HTTP/1.1" 200 648
2025-07-25 21:16:16,541 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 21:16:16,589 [INFO] users: [proliance] Retrieved 8 user activity records
2025-07-25 21:16:16,596 [INFO] django.server: "GET /api/users/user-activities/?limit=10 HTTP/1.1" 200 2099
2025-07-25 21:16:16,684 [ERROR] django.request: Internal Server Error: /schedule/api/schedules/upcoming/
2025-07-25 21:16:16,686 [ERROR] django.server: "GET /schedule/api/schedules/upcoming/ HTTP/1.1" 500 46
2025-07-25 21:16:16,820 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 21:16:16,835 [INFO] django.server: "GET /api/groups/groups/?limit=10 HTTP/1.1" 200 648
2025-07-25 21:16:16,882 [ERROR] django.request: Internal Server Error: /payments/payment-config
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "payments_paymentconfig" does not exist
LINE 1: ...d_at", "payments_paymentconfig"."updated_at" FROM "payments_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\payments\views.py", line 54, in list
    config = PaymentConfig.objects.first()
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1104, in first
    for obj in queryset[:1]:
               ~~~~~~~~^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "payments_paymentconfig" does not exist
LINE 1: ...d_at", "payments_paymentconfig"."updated_at" FROM "payments_...
                                                             ^

2025-07-25 21:16:16,899 [ERROR] django.server: "GET /payments/payment-config HTTP/1.1" 500 30023
2025-07-25 21:16:17,021 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 21:16:19,533 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 2079
2025-07-25 21:16:19,761 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=10 HTTP/1.1" 200 2079
2025-07-25 21:16:21,535 [INFO] django.server: "GET /api/courses/enrollments/all/ HTTP/1.1" 200 52
2025-07-25 21:16:21,535 [INFO] django.server: "GET /api/courses/courses/least_popular/ HTTP/1.1" 200 45
2025-07-25 21:16:21,560 [INFO] django.server: "GET /api/courses/courses/most_popular/ HTTP/1.1" 200 45
2025-07-25 21:16:21,600 [INFO] django.server: "GET /api/courses/categories/ HTTP/1.1" 200 393
2025-07-25 21:16:21,796 [INFO] django.server: "GET /api/courses/enrollments/all/ HTTP/1.1" 200 52
2025-07-25 21:16:21,836 [INFO] django.server: "GET /api/courses/courses/most_popular/ HTTP/1.1" 200 45
2025-07-25 21:16:21,839 [INFO] django.server: "GET /api/courses/categories/ HTTP/1.1" 200 393
2025-07-25 21:16:21,840 [INFO] django.server: "GET /api/courses/courses/least_popular/ HTTP/1.1" 200 45
2025-07-25 21:16:23,308 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 2079
2025-07-25 21:16:23,402 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=10 HTTP/1.1" 200 2079
2025-07-25 21:16:26,634 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 2079
2025-07-25 21:16:26,686 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=10 HTTP/1.1" 200 2079
2025-07-25 21:16:30,108 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 2079
2025-07-25 21:16:30,610 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=10 HTTP/1.1" 200 2079
2025-07-25 21:16:30,628 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=1000 HTTP/1.1" 200 2079
2025-07-25 21:16:33,043 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=1000 HTTP/1.1" 200 2079
2025-07-25 21:16:41,488 [INFO] django.server: "GET /api/users/users/?page_size=1000 HTTP/1.1" 200 410
2025-07-25 21:16:41,540 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 21:16:41,575 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 648
2025-07-25 21:16:41,632 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-07-25 21:16:42,111 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 21:16:42,187 [INFO] django.server: "GET /api/users/users/?page_size=1000 HTTP/1.1" 200 410
2025-07-25 21:16:42,188 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 648
2025-07-25 21:16:42,197 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-07-25 21:16:42,346 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 21:16:42,437 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-07-25 21:16:42,467 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 648
2025-07-25 21:16:42,550 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 21:16:42,661 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-07-25 21:16:42,724 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 648
2025-07-25 21:16:42,776 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 21:16:42,840 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-07-25 21:16:42,958 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 409
2025-07-25 21:16:43,018 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-07-25 21:16:44,811 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 2079
2025-07-25 21:16:48,497 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 2079
